### ISSUE TITLE
Crash on mac

### ISSUE THREAD

**Issue by AlexanderwithaA** [mt1006/mc-ar-mod#1]
Hopefully this will help you get the mod working on Mac, I’m running this with mc 1.20.1, fabric api 0.91.0, fabric loader 0.15.3, and version 0.1 of this mod. The Mac is a 13” mid 2013 macbook.
I’m getting a crash on my with these errors:

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1046)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:68)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:847)
	at net.minecraft.class_310.<init>(class_310.java:483)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.minecraft.client.main.Main.md3ab899$ar_mod$lambda$atMain$0$0(Main.java:526)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: GLFW may only be used on the main thread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.<clinit>(EventLoop.java:30)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1046)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:68)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:847)
	at net.minecraft.class_310.<init>(class_310.java:483)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.minecraft.client.main.Main.md3ab899$ar_mod$lambda$atMain$0$0(Main.java:526)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mt1006** [comment]
Generally, I haven't tried it on MacOS yet, so I expected it to have issues. I'll try to fix it in 0.2, probably in the next week or two.

**Comment by mt1006** [comment]
Sorry for it taking so long, but I had problems with getting a GPU acceleration on a VM. I'll try to fix it sometime in the future, but I don't know when it will be.
